version: "2"

linters:
  default: all
  disable:
  - exhaustruct
  - nlreturn
  settings:
    depguard:
      rules:
        main:
          allow:
          - $gostd
          - github.com/hashfunc/pod-termination-handler
          - github.com/IBM/fp-go
          - k8s.io
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$

formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(github.com/hashfunc/pod-termination-handler)
    gofumpt:
      module-path: github.com/hashfunc/pod-termination-handler
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
